swagger: '2.0'
info:
  title: Fury Bridge - REST API
  description: A REST interface for state queries
  version: 0.0.0
externalDocs:
  description: GitHub
  url: https://github.com/Fury-Labs/fury-bridge
host: localhost:1317
schemes:
  - http
